events {}

http {

    limit_req_zone $binary_remote_addr
                   zone=fuel_limit:10m
                   rate=10r/s;

    upstream fuel_backend {
        server fuel-app-1:3015;
        server fuel-app-2:3015;
    }

    server {

        listen 80;

        location / {

            limit_req zone=fuel_limit
                      burst=20
                      nodelay;

            proxy_pass http://fuel_backend;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
