server:
  port: 3015
spring:
  task:
    scheduling:
      enabled: true
  application:
    name: fuelnet
  datasource:
    url: jdbc:postgresql://postgres:5432/fuelnetdb
    username: fuelnet
    password: fuelnet123
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.zoho.com
    port: 587
    username: santiago.mendoza@santimendoza.com
    password: Rhgvq1EEnjcP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
scraper:
  python:
    path: /usr/bin/python3
  script:
    path: /app/price_scraping.py
